version: '3.8'

services:
  # 1. Service Discovery (Eureka)
  discovery-service:
    build:
      context: .
      args:
        SERVICE_NAME: discovery-service
    ports:
      - "8761:8761"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - ai-accuracy-net

  # 2. Circuit Breaker Service
  circuit-breaker-service:
    build:
      context: .
      args:
        SERVICE_NAME: circuit-breaker-service
    ports:
      - "8083:8083"
    depends_on:
      discovery-service:
        condition: service_healthy
    environment:
      # Eureka 서버 주소 다시 추가
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
    networks:
      - ai-accuracy-net

  # 3. AI Adapter Service
  ai-adapter-service:
    build:
      context: .
      args:
        SERVICE_NAME: ai-adapter-service
    ports:
      - "8082:8082"
    depends_on:
      discovery-service:
        condition: service_healthy
    environment:
      # Eureka 서버 주소 다시 추가
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    networks:
      - ai-accuracy-net

  # 4. Core Service
  core-service:
    build:
      context: .
      args:
        SERVICE_NAME: core-service
    ports:
      - "8081:8081"
    depends_on:
      discovery-service:
        condition: service_healthy
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=ai_accuracy_db
      - DB_USERNAME=user
      - DB_PASSWORD=password
      - SPRING_RABBITMQ_HOST=rabbitmq
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
    networks:
      - ai-accuracy-net

  # 5. Database (MySQL)
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ai_accuracy_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ai-accuracy-net

  # 6. Redis
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ai-accuracy-net

  # 7. RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
      - "61613:61613"
    volumes:
      - ./enabled_plugins:/etc/rabbitmq/enabled_plugins
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running", "-q"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ai-accuracy-net

networks:
  ai-accuracy-net:
    driver: bridge

volumes:
  db-data:
